from fastapi.testclient import TestClient
from io import BytesIO
from PIL import Image

from app.dependencies import get_classifier_model
from app.dependencies import get_cifar10_diffusion_generator
from app.dependencies import get_cifar10_energy_generator
from app.dependencies import get_embedding_model
from app.dependencies import get_mnist_image_generator
from app.dependencies import get_rnn_model
from app.main import app


class FakeEmbeddingModel:
    def get_embedding(self, input_word):
        return [0.1, 0.2, 0.3]


def override_embedding_model():
    return FakeEmbeddingModel()


class FakeClassifierModel:
    def predict(self, image):
        return {
            "label": "cat",
            "class_index": 3,
            "confidence": 0.9,
        }


def override_classifier_model():
    return FakeClassifierModel()


class FakeRNNModel:
    def generate_text(self, start_word, length):
        return f"{start_word} generated by rnn {length}"


def override_rnn_model():
    return FakeRNNModel()


class FakeMNISTImageGenerator:
    def generate_digits(self, num_images):
        image = Image.new("L", (1, 1), color=255)
        buffer = BytesIO()
        image.save(buffer, format="PNG")
        return buffer.getvalue()


class MissingCheckpointImageGenerator:
    def generate_digits(self, num_images):
        raise RuntimeError(
            "MNIST GAN checkpoint not found. Run "
            "`uv run python -m scripts.train_mnist_gan` first."
        )


def override_mnist_image_generator():
    return FakeMNISTImageGenerator()


def override_missing_checkpoint_image_generator():
    return MissingCheckpointImageGenerator()


class FakeCIFAR10Generator:
    def generate_images(self, num_images):
        image = Image.new("RGB", (2, 2), color="blue")
        buffer = BytesIO()
        image.save(buffer, format="PNG")
        return buffer.getvalue()


class MissingCIFAR10CheckpointGenerator:
    def generate_images(self, num_images):
        raise RuntimeError("CIFAR-10 checkpoint not found. Run training first.")


def override_cifar10_generator():
    return FakeCIFAR10Generator()


def override_missing_cifar10_generator():
    return MissingCIFAR10CheckpointGenerator()


client = TestClient(app)


def test_root_returns_status():
    response = client.get("/")

    assert response.status_code == 200
    assert response.json() == {"status": "ok", "service": "sps-genai"}


def test_generate_returns_generated_text():
    response = client.post(
        "/generate",
        json={"start_word": "the", "length": 3},
    )

    assert response.status_code == 200
    assert "generated_text" in response.json()


def test_generate_rejects_invalid_length():
    response = client.post(
        "/generate",
        json={"start_word": "the", "length": 0},
    )

    assert response.status_code == 422


def test_generate_with_rnn_returns_generated_text():
    app.dependency_overrides[get_rnn_model] = override_rnn_model

    response = client.post(
        "/generate_with_rnn",
        json={"start_word": "the", "length": 5},
    )

    app.dependency_overrides.clear()

    assert response.status_code == 200
    assert response.json() == {"generated_text": "the generated by rnn 5"}


def test_generate_digit_returns_png_image():
    app.dependency_overrides[get_mnist_image_generator] = override_mnist_image_generator

    response = client.post(
        "/generate_digit",
        json={"num_images": 4},
    )

    app.dependency_overrides.clear()

    assert response.status_code == 200
    assert response.headers["content-type"] == "image/png"
    assert response.content.startswith(b"\x89PNG")


def test_generate_digit_rejects_invalid_num_images():
    response = client.post(
        "/generate_digit",
        json={"num_images": 0},
    )

    assert response.status_code == 422


def test_generate_digit_returns_503_when_checkpoint_is_missing():
    app.dependency_overrides[
        get_mnist_image_generator
    ] = override_missing_checkpoint_image_generator

    response = client.post(
        "/generate_digit",
        json={"num_images": 4},
    )

    app.dependency_overrides.clear()

    assert response.status_code == 503
    assert "train_mnist_gan" in response.json()["detail"]


def test_embedding_returns_vector_metadata():
    app.dependency_overrides[get_embedding_model] = override_embedding_model

    response = client.post(
        "/embedding",
        json={"word": "example"},
    )

    app.dependency_overrides.clear()

    assert response.status_code == 200
    assert response.json() == {
        "word": "example",
        "dimension": 3,
        "embedding": [0.1, 0.2, 0.3],
    }


def test_classify_returns_prediction():
    image = Image.new("RGB", (64, 64), color="red")
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    buffer.seek(0)

    app.dependency_overrides[get_classifier_model] = override_classifier_model

    response = client.post(
        "/classify",
        files={"file": ("sample.png", buffer, "image/png")},
    )

    app.dependency_overrides.clear()

    assert response.status_code == 200
    assert response.json() == {
        "label": "cat",
        "class_index": 3,
        "confidence": 0.9,
    }


def test_generate_energy_returns_png_image():
    app.dependency_overrides[
        get_cifar10_energy_generator
    ] = override_cifar10_generator

    response = client.post("/generate_energy", json={"num_images": 4})

    app.dependency_overrides.clear()

    assert response.status_code == 200
    assert response.headers["content-type"] == "image/png"
    assert response.content.startswith(b"\x89PNG")


def test_generate_diffusion_returns_png_image():
    app.dependency_overrides[
        get_cifar10_diffusion_generator
    ] = override_cifar10_generator

    response = client.post("/generate_diffusion", json={"num_images": 4})

    app.dependency_overrides.clear()

    assert response.status_code == 200
    assert response.headers["content-type"] == "image/png"
    assert response.content.startswith(b"\x89PNG")


def test_cifar10_generation_rejects_too_many_images():
    response = client.post("/generate_energy", json={"num_images": 17})

    assert response.status_code == 422


def test_cifar10_generation_returns_503_for_missing_checkpoint():
    app.dependency_overrides[
        get_cifar10_diffusion_generator
    ] = override_missing_cifar10_generator

    response = client.post("/generate_diffusion", json={"num_images": 4})

    app.dependency_overrides.clear()

    assert response.status_code == 503
    assert "checkpoint not found" in response.json()["detail"]
